[Chore] #151 - Font 정리 및 편의 메서드 추가
Team-WSS/WSS-iOS pull request #152
Opened 2024-05-15 07:22 UTC by Naknakk

### ⭐️Issue
close #151 
<br/>

### 🌟Motivation
- 폰트 추가 작업 중 폰트와 행간자간 설정은 언제나 같이 가기 때문에, 둘을 한번에 할 수 있는 편의 메서드를 추가하였습니다.
<br/>

### 🌟Key Changes
- 디자인 시스템 변경에 따른 폰트 변경사항, 추가사항 반영
- 폰트 설정과 행간자간 설정을 함께 할 수 있는 편의 메서드 UILabel Extension에 추가.
- 추가한 편의 메서드
<img width="582" alt="Screenshot 2024-05-15 at 15 51 43" src="https://github.com/Team-WSS/WSS-iOS/assets/87518742/2c963db4-0678-44b0-9697-18a7a353c7d3">

- 메서드 사용 방식

![image](https://github.com/Team-WSS/WSS-iOS/assets/87518742/f5938856-5377-4c66-ad2f-a7d848d5f219)

<br/>

### 🌟To Reviewer
- 간단한 변경사항입니다 ! 좋은 의견 환영합니다.
<br/>

2024-05-19 02:30 UTC, ena-isme approved these changes
수고하셨습니다 :)

2024-05-19 06:13 UTC, Guryss requested changes
함수 만드시느라 수고 많았습니당!
수정할 부분 있으니 확인해주세요~~~

2024-05-19 06:13 UTC, Guryss commented on WSSiOS/WSSiOS/Resource/Extensions/UILabel+.swift
> +                .lineSpacing(spacingPercentage: 150)
<img width="578" alt="image" src="https://github.com/Team-WSS/WSS-iOS/assets/102604192/0ed5b0a7-7e3c-4522-95fc-e84d18f94904">
W1;
`title3` line Spacing 100 입니다! 수정부탁드려요!!

2024-05-19 06:13 UTC, Guryss commented on WSSiOS/WSSiOS/Resource/Extensions/UILabel+.swift
> +        }
W1;
Body1 인데 폰트가 Body2로 설정되어있어용~

2024-05-19 10:16 UTC, ena-isme commented on WSSiOS/WSSiOS/Resource/Extensions/UILabel+.swift
> +                .lineSpacing(spacingPercentage: 150)
왕 꼼꼼이 💖

2024-05-20 10:58 UTC, Guryss approved these changes
수고많았어욥!!!!!!!!!!!

2024-05-21 08:17 UTC, merged