[Design] #171 - FeedDetailView UI 1차 구현
Team-WSS/WSS-iOS pull request #180
Opened 2024-07-08 08:30 UTC by Guryss

### ⭐️Issue
close #171 
<br/>

### 🌟Motivation

<br/>

### 🌟Key Changes

<br/>

```swift
abc
```
<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-07-10 05:40 UTC, ena-isme reviewed
수고하셨습니다!
아직 ViewModel 에는 데이터를 받아오는 것만 되어있어서 API 연결 어떻게 하실지 넘 궁금하네용 ><

2024-07-10 05:40 UTC, ena-isme commented on WSSiOS/WSSiOS/App/SceneDelegate.swift
> +        let navigationController = UINavigationController(rootViewController: FeedDetailViewController(viewModel: FeedDetailViewModel(feedRepository: TestFeedRepository())))
돌려놓지 않을 위험 방지 Review 입니당

2024-07-10 05:40 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Feed/FeedView/FeedAssistantView/FeedContentView.swift
> +final class FeedContentView: UIView {
W3
남이 짠 View 도 뚝딱뚝딱 수정 잘하는 똑똑이 🤓
제꺼까지 해주셔서 감사합니둥,,, 💖

2024-07-10 05:40 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailProfileView.swift
> +        //userProfileImageView.kfSetImage(url: data.userProfileImage)
W2
이런 부분 저는 그냥 쿠로미 넣어요,, 교동이 넣어주세요 ,,

2024-07-10 05:40 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailProfileView.swift
> +        }
W3
서연이 코드 볼 때마다 이 부분 아주 야무지네요

2024-07-10 05:40 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailReplyCollectionViewCell.swift
> +    private let threeDotsButton = UIButton()
W1
이 부분 제가 만들어두었던 dropdownButton(원래는 View 였는데 Button 으로 수정했구, 아직 머지 안했습니다!) 으로 수정해도 좋을 것 같습니다!

2024-07-10 05:40 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
> +    private var dotsButton = UIButton()
W1 (이지만 수정은 나중에 ,,,)
이 부분도 추후 dropDownButton 으로 고쳐주시면 좋을 것 같아요!
위에서 썼던 View 에는 dropDownButton 으로 설정해두어도 잘 작동할 텐데 아직 navigationBar 에 넣는 dropDownButton 은 에러가 나가주구 여기는 나중에 수정 부탁드릴게요!

2024-07-10 05:40 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
> +    }
저도 이 부분 이렇게 해두었어요,,, ㅠ
혹시 PublishRelay 가 안되는 정확한 이유를 아실까요 ,,? 
PublishRelay로 하려다가 잘 안되어서요!

2024-07-13 14:36 UTC, Guryss commented on WSSiOS/WSSiOS/App/SceneDelegate.swift
> +        let navigationController = UINavigationController(rootViewController: FeedDetailViewController(viewModel: FeedDetailViewModel(feedRepository: TestFeedRepository())))
확인했숩니당

2024-07-13 14:37 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailProfileView.swift
> +        //userProfileImageView.kfSetImage(url: data.userProfileImage)
ㅇㅎㅇㅎ!! ㅈㅓ도 그럼 수정을 해보도록 ㅋㅋ

2024-07-13 15:11 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
> +    private var dotsButton = UIButton()
네넹!!

2024-07-16 18:18 UTC, Guryss commented
![Simulator Screenshot - iPhone 13 mini - 2024-07-17 at 03 14 34](https://github.com/user-attachments/assets/117eb19d-6d1c-4f78-8387-88a56b2f9371)

ReplyCollectionViewCell에서 댓글의 줄 수가 1줄 넘어갈 때 Cell 높이 동적으로 조절될 수 있도록 구현 완료 했습니다!

2024-07-17 13:58 UTC, hyowon612 reviewed
수고 많았슴둥 깔끔하네용 😙

2024-07-17 13:58 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/Feed/FeedView/FeedAssistantView/FeedNovelView.swift
> +            $0.applyWSSFont(.title3, with: $0.text)
W1
여기 텍스트 적용하는 부분이 중복인거 같아요!

2024-07-17 13:58 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailReplyView.swift
> +                                               collectionViewLayout: UICollectionViewLayout())
W2
혹시 이 댓글 뷰 콜렉션뷰로 구현한 특별한 이유가 있을까용??
생긴걸로 봤을때는 테이블뷰로도 구현 가능할거 같아서여!!
테이블뷰셀은 따로 처리 안해두 dynamic height가 적용되기두 하구용

2024-07-17 13:58 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailReplyCollectionViewCell.swift
> +            $0.numberOfLines = 0
W2
여기 numberOfLines는 위에랑 중복인데 혹시 폰트 적용하면 속성이 초기화돼서 다시 적용해주는건가욤?

2024-07-17 13:58 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
> +    private let feedProfileData = BehaviorRelay<Feed>(value: Feed(userProfileImage: "", userNickName: "", createdDate: "", content: "", novelTitle: "", novelRating: 0, novelRatingCount: 0, genres: [.
W2
초기값이 필요한 객체가 아니라면 PublishRelay로 구현해도 될거 같아용

2024-07-17 15:55 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Feed/FeedView/FeedAssistantView/FeedNovelView.swift
> +            $0.applyWSSFont(.title3, with: $0.text)
이거 쿠로미꺼긴 한데 제가 수정해놓을게요옹

2024-07-17 16:44 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
> +    private let feedProfileData = BehaviorRelay<Feed>(value: Feed(userProfileImage: "", userNickName: "", createdDate: "", content: "", novelTitle: "", novelRating: 0, novelRatingCount: 0, genres: [.
@hyowon612 

그래서 일단 `BehaviorRelay<Feed?>(value: nil)`로 처리하였습니다 !

`PublishRelay`가 안되는 이유는 더 찾아봐야 할 것 같지만.. .제가 생각한 이유는 Publish는 구독 이후의 이벤트만을 방출하고, `BehaivorRelay`는 구독 이전 최근 값을 방출해주니까 그런 차이점 때문에 그런 것이 아닐지 ...?

2024-07-17 16:45 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailReplyCollectionViewCell.swift
> +            $0.numberOfLines = 0
넹 마자요. 그래서 위에 코드는 삭제했습니당

2024-07-17 16:45 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailReplyView.swift
> +                                               collectionViewLayout: UICollectionViewLayout())
맞는데, 제가 테이블뷰 셀간의 간격을 22로 잡아야 했는데 해당 부분이 적용이 안되더라구요.. 
그래서 그냥 바아로 컬뷰로 턴했습니다

2024-07-18 11:21 UTC, ena-isme approved these changes

2024-07-18 11:21 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
> +    private let feedProfileData = BehaviorRelay<Feed>(value: Feed(userProfileImage: "", userNickName: "", createdDate: "", content: "", novelTitle: "", novelRating: 0, novelRatingCount: 0, genres: [.
저도 이부분에서 애먹어서 BehaviorRelay 로 바꿔주었고, 구리스와 같은 생각입니둥!

2024-07-20 11:45 UTC, Naknakk reviewed
고생했습니다!
BehaviorRelay로 서버에서 받아온 데이터를 처리하고 있는데, 제 생각에는 이렇게 하면 서버 통신에 오류가 있는 경우 처리를 할 수 없기 때문에 좋지 않아 보여요 ..!!

Subject로 바꾸어 onError를 VC상에서 받을 수 있게 하는게 어떨까요?

2024-07-20 11:45 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Data/DTO/FeedDetailResult.swift
W1
Feed와 Comment 둘 모두 서버에서 제공하는 형태와 다른 것 같은데, 의도적으로 이렇게 한건지 궁금합니다! 이러면 나중에 서버 연결할 때 결국 다 수정해야 할 것 같아서요 !

2024-07-20 11:45 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Data/Repository/FeedRepository.swift
> +                                                                                                 nickname: "지원입니둥",
W1

TotalFeeds 라는 구조체 명이 지금보니 굉장히 어색하구뇽 . . 그리고 단건 조회시 서버에서 받는 구조와 동일하구요. 그래서
소소피드 전체 조회 Result인 TotalFeed 구조체는 그대로 두고, 단건 조회의 Result는 TotalFeeds -> Feed로 변경하는게 어떨까요? 
그래서 이 Feed를 전체조회(@ena-isme 부분)와 단건조회(@Guryss 부분) 두 곳에서 모두 쓰면 될 것 같다구 생각합니다

2024-07-20 11:45 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Data/Repository/FeedRepository.swift
> +    func getSingleFeedComments() -> Observable<[Comment]>
W1
서버에서 받는 Result와 다른 것에 이어서 메서드 자체도 실제 API에서 필요로 하는 feedId를 input으로 받게 만들어놔야 할 것 같아요 ! 그래야 나중에 서버만 연결하면 되니까요~!~

2024-07-20 11:45 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailContentView.swift
> +        }
W1

FeedNovelView의 background Color가 이미 wssPrimary20이라 없어도 될 것 같아용~

2024-07-20 11:45 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailContentView.swift
> +        let genres = data.genres.map { $0.withKorean }.joined(separator: ", ")
W1
Swift 답고 깔쌈하고 멋지네요

2024-07-20 11:45 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailReplyCollectionViewCell.swift
> +        }
W1
이 버튼의 세로 위치가 전체 셀의 중앙이 맞는지 궁금합니다! 디쟌쌤들한테 한번 확인해봐야 할 것 같아요.
제가 보기엔 내려가있는게 어색해서, $0.centerY.equalTo(userProfileImageView.snp.centerY) 이런 식으로 가야할 것 같아요 ..!!
댓글이 한줄일 때의 버튼 위치가 그대로 댓글이 여러줄일 때도 유지되어있어야 더 자연스러울 것 같다는 느낌이 듭니다!

2024-07-20 11:45 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailView.swift
> +            $0.height.greaterThanOrEqualTo(self.snp.height).priority(.low)
W1
정확히 설명은 못하겠지만 이 부분 코드가 없어도 잘 작동할겁니당...! 스크롤 뷰에 넣어주는 뷰는 자체 뷰 높이가 잘 잡혀 있다면 이런 제약은 추가해주지 않아도 될거에요!

2024-07-20 11:45 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
> +    private let comments = BehaviorRelay<[Comment]>(value: [])
W1
해당 변수는 사용하지 않는 것 같네요 !

2024-07-20 11:45 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
> +    private var dotsButton = UIButton()
W2
효원이 코드를 보니 네비게이션용 버튼들도 View에 미리 선언해두니 VC에 rootView말고 UIComponent가 없어서 깔끔하더라구용~

2024-07-20 11:45 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
> +        self.view.backgroundColor = .wssWhite
W1
이런 뷰 관련 코드는 FeedDetailView에서 해줘도 될 것 같아용!

2024-07-20 11:45 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
> +    }
W3
줄 높이에 따라 셀 높이 값 얻는 과정 잘 구현했네용 멋져요~~

2024-07-21 06:42 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
> +    private var dotsButton = UIButton()
옹 확인해서 반영해두겠습니다

2024-07-21 06:48 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailReplyCollectionViewCell.swift
> +        }
오홍 그렇네요!!! 일단 이렇게 수정해두겠습니다 :)

2024-07-21 06:52 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailView.swift
> +            $0.height.greaterThanOrEqualTo(self.snp.height).priority(.low)
그렇네용! 감사합니당!

2024-07-21 10:22 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Data/Repository/FeedRepository.swift
> +                                                                                                 nickname: "지원입니둥",
이 부분에 대해서는 지원이언니랑 다시 한번 얘기해보고 합쳐서 코드 올릴게요!

2024-07-28 14:45 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Data/Repository/FeedRepository.swift
> +                                                                                                 nickname: "지원입니둥",
우선 변경치 않고 그대로 진행하겠습니다!

2024-08-04 16:59 UTC, hyowon612 approved these changes
엘지티엠입니다룽 👼🏻

2024-08-05 05:19 UTC, Naknakk requested changes
Subject로 바꾸어 onError를 VC상에서 받을 수 있도록 수정이 아직 진행되지 않은거겠죵! ?

2024-08-05 08:40 UTC, Guryss commented
> Subject로 바꾸어 onError를 VC상에서 받을 수 있도록 수정이 아직 진행되지 않은거겠죵! ?

엇 수정해서 커밋만 해놓고 푸쉬를 안했나봐요. 오늘 푸쉬해서 노티드리겠습니당!

2024-08-17 13:58 UTC, Naknakk approved these changes

2024-08-17 14:02 UTC, merged