[Design] #189 - DetailSearchInfoView (상세탐색-정보뷰) UI 구현
Team-WSS/WSS-iOS pull request #190
Opened 2024-07-21 13:44 UTC by Guryss

### ⭐️Issue
close #189 
<br/>

### 🌟Motivation
- DetailSearchInfoView (상세탐색-정보뷰) UI 구현했습니다. 
<br/>

### 🌟Key Changes

<br/>

```swift
abc
```
<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-07-24 05:47 UTC, ena-isme reviewed
장하다 
<img width="210" alt="스크린샷 2024-07-24 오후 2 47 18" src="https://github.com/user-attachments/assets/3a1d7c16-a643-4842-8168-db291c690051">

2024-07-24 05:47 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchBottomView.swift
> +    }
W2
구조가 특이하네용, 맨 마지막에 슈퍼뷰로 넣어준 이유가 있을까요 ??

2024-07-24 05:47 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewModel/DetailSearchViewModel.swift
> +            .map { $0?.height ?? 0 }.asDriver(onErrorJustReturn: 0)
W1
.asDriver 한 줄 띄고 작성해주세용

2024-07-24 05:47 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewModel/DetailSearchViewModel.swift
> +import RxGesture
W1
import RxReleay 도 추가해주세용!

2024-07-24 05:47 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewController/DetailSearchViewController.swift
> +                cell.bindData(genre: element)
W1
쉼표 다음에 cellType 띄어쓰기 해주세요~

2024-07-24 05:47 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchInfoView.swift
> +    private let genreTItleLabel = UILabel()
W1
여기 중간에 대문자가 들어갔네용 💖

2024-07-24 12:42 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewController/DetailSearchViewController.swift
> +    }
요 부분 쇽샥 💖

2024-07-24 12:55 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewController/DetailSearchViewController.swift
> +    }
저도 윤학오빠꺼 쇽샥 해온거에요. 굿굿 >3<

2024-07-25 05:58 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchBottomView.swift
> +    }
스택뷰 - 버튼뷰 - 이미지/라벨 
아래부터 말하면 이러한 계층 구조로 이해했는데
슈퍼뷰에 스택뷰를 깔고 올리는 게 아닌
버튼뷰부터 먼저 구현해주고 마지막에 슈퍼뷰에 addSubview 한 이유가 있을까요?
레이아웃 잡을 땐 슈퍼뷰 먼저 잡고 상세를 잡아주는 것처럼 보여서요 🤓🤓

2024-07-25 05:58 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewModel/DetailSearchViewModel.swift
> +import RxGesture
저의 지식 미숙입니다 ㅎㅋ

2024-07-25 06:02 UTC, ena-isme approved these changes

2024-07-25 06:15 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchBottomView.swift
> +    }
아하 ! 전 주로 마지막에 슈퍼뷰에 넣어주긴 해요..

뭔가 완성품을 슈퍼뷰에 붙여주는게 좋은데, 완성품이 아닌 애를 슈퍼뷰에 넣어주면 뭔가 아쉽더라구요.
그래서 자식뷰들을 다 구성해놓은 다음에 슈퍼뷰에 최종적으로 올려주는 것을 선호합니다!

2024-07-26 09:34 UTC, ena-isme commented
@Guryss 
DetailSearchGenre 이 부분 마이페이지에서도 쓰고 싶은데
혹시 GenreList 로 네이밍 변경하는 건 어떨까요?
전체와 etc 들어간 장르는 ExtendedGenreList 로 하는건 ,,, ?

2024-07-27 17:34 UTC, Guryss commented
> @Guryss DetailSearchGenre 이 부분 마이페이지에서도 쓰고 싶은데 혹시 GenreList 로 네이밍 변경하는 건 어떨까요? 전체와 etc 들어간 장르는 ExtendedGenreList 로 하는건 ,,, ?

네이밍 변경하는 것 좋습니다! 근데 전체 피드 조회에는 장르 리스트에 전체, 기타가 추가되어있어서 해당 부분과 구분을 지어서 네이밍 하는 게 좋을 것 같아요. 글고 enum 열거형이라 List를 넣으면 배열이랑 헷갈릴 것 같긴 해용!

`Genre`로 열거형 만들고, 전체 피드 상단에 보이는 장르들을 `FeedGenre`라고 네이밍 하는 건 어떨까요?
`Genre`가 주로 보편적으로 사용되는 장르이니!

2024-07-28 07:34 UTC, Naknakk commented
> > @Guryss DetailSearchGenre 이 부분 마이페이지에서도 쓰고 싶은데 혹시 GenreList 로 네이밍 변경하는 건 어떨까요? 전체와 etc 들어간 장르는 ExtendedGenreList 로 하는건 ,,, ?
> 
> 네이밍 변경하는 것 좋습니다! 근데 전체 피드 조회에는 장르 리스트에 전체, 기타가 추가되어있어서 해당 부분과 구분을 지어서 네이밍 하는 게 좋을 것 같아요. 글고 enum 열거형이라 List를 넣으면 배열이랑 헷갈릴 것 같긴 해용!
> 
> `Genre`로 열거형 만들고, 전체 피드 상단에 보이는 장르들을 `FeedGenre`라고 네이밍 하는 건 어떨까요? `Genre`가 주로 보편적으로 사용되는 장르이니!
> 
> @ena-isme

혹시 이 부분 Genre라는 열거형 내에 FeedGenre 라는 [Genre] 타입 static 변수를 만드는건 어떨까요 ?

2024-08-04 16:54 UTC, hyowon612 approved these changes
엘지티엠~~~~~~~~~~~~~~~

2024-08-04 16:54 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/Base/KeywordLabel/KeywordBox.swift
> +final class KeywordBox: UIView {
W2
KeywordBoxView로 네이밍 수정~ 어떨까여~

2024-08-04 16:54 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchCell/DetailSearchInfoGenreCollectionViewCell.swift
> +    private let genreKeywordView = KeywordViewManager.shared.link()
W2
마크주석 components로 달아야할듯!

2024-08-04 16:54 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchView.swift
> +
W2
빈줄 없애쥬

2024-08-05 09:28 UTC, Naknakk requested changes
UI 관련 코멘트 많이 남겼습니당 확인해주세요! 아직VC, VM은 못봤는데 일정 후에 돌아와서 보겠습니당 . .

2024-08-05 09:28 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchHeaderView.swift
W1
- 전체적으로 레이아웃 오류가 있습니다! 
    - updateUnderLineView 메서드에서 라벨과의 offset이 빠져서 하단 바와 라벨이 너무 가까워요.
    - 두 라벨간의 간격이 29.5입니다! (피그마에서 프레임이 이상하게 잡혀있지만, 두 라벨만 비교하면 29.5입니다!)
- newImageView도 tintColor가 흰색으로 잘못 들어가있어서 현재 뷰에서 보이지 않고 있구 위치 업데이트도 되지 않고 있습니당
- newImageView에 쓰는 에셋 크기가 5x4로 잘못 들어와있습니당. 제대로 추출 할 수 있게 디자인 시스템에 추가해달라고 요청해야할 것 같아요
- 뷰의 최하단은 UnderLineView이니, KeywordLabel에서 bottom.equalToSuperview()를 잡아주는게 아니라
underLineView에서 bottom.equalToSuperview()을 해줘야 할 것 같습니당!

2024-08-05 09:28 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchInfoView.swift
> +        }
W1
두번 들어가있어용 삭제해주세요 !

2024-08-05 09:28 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchInfoView.swift
> +            $0.top.equalTo(statusStackView.snp.bottom).offset(32)
W1
32아니구 42입니다!

2024-08-05 09:28 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchInfoView.swift
> +            $0.top.equalTo(genreCollectionView.snp.bottom).offset(32)
W1
여기 32 아니구 42입니당!

2024-08-05 09:28 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchInfoView.swift
> +        }
W1
CollectionView 높이가 88로 고정된 채 바뀌는 일이 없다면 없어도 될 것 같아요!

2024-08-05 09:28 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchView.swift
> +                $0.top.leading.equalToSuperview().inset(34)
W1
이부분 leading이 피그마에는 34.97로 잡혀있는데..이 소수점 패딩도 그렇고 프레임이 이상하게 잡혀 있어서 디자인한테 수정 요청해도 좋을 것 같아용

2024-08-05 09:28 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchView.swift
> +                $0.height.equalTo(62)
W1
BottomView Height가 중복으로 잡혀있어용 없어도 될 것 같아요 !

2024-08-05 09:28 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchView.swift
> +            $0.layer.cornerRadius = 15
W1
이게 전체에 cornerRadius 주면 SE 같은 경우 하단에 굴곡으로 빵꾸가 생긴답니당 ... 상단에만 코너 Radius주거나 길이를 더 길게 해주거나 해서 숨기면 좋을 것 같아요

2024-08-17 13:01 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Base/KeywordLabel/KeywordBox.swift
> +final class KeywordBox: UIView {
나머지 키워드뷰 친구들 네이밍이 `KeywordTag`, `KeywordLink`, `KeywordLabel`이라 따로 View를 안붙였어용!

2024-08-17 13:10 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchInfoView.swift
> +            $0.top.equalTo(statusStackView.snp.bottom).offset(32)
고맙습니당

2024-08-17 13:22 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchView.swift
> +                $0.top.leading.equalToSuperview().inset(34)
우선.... 34로 해둘레ㅐ용

2024-08-17 13:44 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchHeaderView.swift
1. 해당 부분 확인해보니 라벨의 lineHeight과 underLine의 Height을 감안하여 총 간격이 6으로 확인했습니다! 뷰 내 레이아웃엔 `offset(6)`으로 잡아놨는데 `updateUnderLineView`에는 안해놨네요.... 설정해서 레이아웃 수정 해두었습니다!

2. 일부러 흰색으로 두었습니다! 기능 개발할 때 추가할 예정입니다.

3. 요청해두었고 수정해서 넣어두겠습니다.

4. 꼼꼼한 코드리뷰 감사합니다. (_ _) 최고 낙낙!!!!!

2024-08-17 13:47 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchHeaderView.swift
<img width="271" alt="image" src="https://github.com/user-attachments/assets/1fbd5121-d4db-41fa-8fc1-9c6b0b4156bd">

이미지 수정해서 넣어두었습니다. 최공

2024-08-19 01:34 UTC, Naknakk requested changes
수정하느라 고생했어요! 마지막 하나만 더 확인해주세요 !

2024-08-19 01:34 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchHeaderView.swift
>              $0.leading.equalTo(infoLabel.snp.trailing).offset(22.5)
P1
infoLabel과 keywordLabel 두 라벨의 간격이 29.5라는 말이었습니당~!~!

2024-08-23 18:03 UTC, Naknakk approved these changes

2024-08-23 18:29 UTC, merged