[Design] #186 - 마이페이지 회원탈퇴 UI 구현
Team-WSS/WSS-iOS pull request #192
Opened 2024-07-24 17:48 UTC by ena-isme

### ⭐️Issue
close #186 
<br/>

### 🌟Motivation

<br/>

### 🌟Key Changes

공용 컴포넌트 수정이 조금 있습니다!
### 1. 띄어쓰기 만으로 이루어져있는지 체크해주는 extension 을 String+ 에 추가하였습니다
<br/>

```swift
// 띄어쓰기만으로 이루어진 Text 인지 체크
    func textIsEmpty() -> Bool {
        let trimmedText = self.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmedText.isEmpty { return true } else { return false }
    }
```
<br/>

### 2. UILabel+ 에서 'lineHeight" 의 에러 핸들링과, 'partialColor' 의 코드를 수정해두었습니다 

<br/>

//lineHeight

Warning 메세지가 뜨길래 에러 핸들링 코드를 추가하였씁니당

```swift
guard !lineHeight.isNaN else {
            print("Error: lineHeight is NaN")
            return self
        }
```

<br/>

//partialColor

기존 이 코드에서 self.label.text 이 부분을 self.attributedString.string 으로 변경하였습니다

```swift
//변경 전
func partialColor(color: UIColor, rangeString: String) -> TextAttributeSet {
        self.attributedString.addAttribute(
            .foregroundColor,
            value: color,
            range: ((self.label.text ?? "") as NSString).range(of: rangeString)
        )
        
        return self
    }

//변경 후
func partialColor(color: UIColor, rangeString: String) -> TextAttributeSet {
        let range = (self.attributedString.string as NSString).range(of: rangeString)
        if range.location != NSNotFound {
            self.attributedString.addAttribute(.foregroundColor, value: color, range: range)
        }
        return self
    }
```

<br/>

//MyPageDeleteIDView
scroll 에서 아래와 같이 기기대응을 해주었습니다.
버튼에만 주고 싶었는데 그러지 못해서 더 좋은 방법 있으면 말씀주세요~!

<br/>

```swift
scrollView.snp.makeConstraints {
            if UIScreen.isSE {
                $0.edges.equalTo(safeAreaLayoutGuide.snp.edges)
            } else {
                $0.edges.equalToSuperview()
            }
        }
```
<br/>

//MyPageDeleteIDRecordView
stackView 의 패딩값을 아래와 같이 주었는데 편해서 공유해봅니다!
layoutMargins 인 UIEdgeInsets 인 반면 directionalLayoutMargins 는 NSDirectionalEdgeInsets 타입이기 때문에 left, right 뿐만 아니라 leading, trailing 으로 대응된다고 합니당

<br/>

```swift
stackView.do {
            $0.isLayoutMarginsRelativeArrangement = true
            $0.directionalLayoutMargins.top = 20
            $0.directionalLayoutMargins.bottom = 20
            $0.setCustomSpacing(5, after: iconImageView)
        }
```
<br/>

### 🌟Simulation

| iPhone SE 3rd  | iPhone 15 Pro | 
|--|--|
|![Simulator Screen Recording - iPhone SE (3rd generation) - 2024-07-25 at 02 47 33](https://github.com/user-attachments/assets/59358e55-3a3a-4359-8a4d-926134d5aa3b)|![Simulator Screen Recording - iPhone 15 Pro - 2024-07-25 at 02 46 45](https://github.com/user-attachments/assets/09528d03-1b89-4528-8de6-9cd032095b2f)|

<br/>

### 🌟To Reviewer

0. 마이페이지 주제에 오늘 하루를 여기에 다 써서 쪼끔 슬펐습니다
1. TableView 가 두 개나 잡히게 되어 MyPageDeleteIDView 가 길어졌습니다,,, 코리에 불편을 드려,,, 슈퍼 쏘리 💖
2. itemSelected 가 안잡히길래 진짜 이랬다 저랬다 다 해봤는데, 알고보니 꾸욱 누르니 되던 ,,, 시뮬에서 꾸-욱 누르지 않아도 바로바로 tap 되는 방법을 아시나요 ? 제께 이상한건가요 ?
3. textView 때문에 아래와 같은 코드가 뜨는데 아래에서 말해준 해결책대로 `.observe(on:MainScheduler.asyncInstance)` 를 사용하면 didBeginEdting, didEndEditing 을 인지하지 못하는 이슈가 발생해요 ,,, 혹시 관련 이슈 경험해보셨다면 텔미 

```swift
⚠️ Reentrancy anomaly was detected.
  > Debugging: To debug this issue you can set a breakpoint in 
....RxSwift/Rx.swift:96 and observe the call stack.
  > Problem: This behavior is breaking the observable sequence grammar. `next (error | completed)?`
    This behavior breaks the grammar because there is overlapping between sequence events.
    Observable sequence is trying to send an event before sending of previous event has finished.
  > Interpretation: This could mean that there is some kind of unexpected cyclic dependency in your code,
    or that the system is not behaving in the expected way.
  > Remedy: If this is the expected behavior this message can be suppressed by adding `.observe(on:MainScheduler.asyncInstance)`
    or by enqueuing sequence events in some other way.
```

<br/>

### 🌟Reference
https://ios-development.tistory.com/654
https://rldd.tistory.com/208 (3번과 관련된 이슈 해결못함)
https://opendoorlife.tistory.com/19
https://ios-development.tistory.com/1498
https://stackoverflow.com/questions/63569113/directionallayoutmargins-on-uiimageview-not-working-inside-horizontal-stack-view
https://developer.apple.com/documentation/uikit/uiview/2865930-directionallayoutmargins
<br/>

2024-07-28 15:12 UTC, hyowon612 reviewed
신이나 화이팅 👯

2024-07-28 15:12 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageDeleteIDRecordView.swift
> +            $0.setCustomSpacing(5, after: iconImageView)
W3
꿀 ~ 🍯

2024-07-28 15:12 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageDeleteIDReasonTableViewCell.swift
> +//  File.swift
W2
주석도 이름 똑가티 바꿔조

2024-07-28 15:12 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageDeleteIDReasonTableViewCell.swift
> +    func isSeleted(isSeleted: Bool) {
W1
select 오타 !!!!

2024-07-28 15:12 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageDeleteIDView.swift
> +    func agreeDeleteIDButtonIsSeleted(isSeleted: Bool) {
W1
select 오타 !!!!

2024-07-28 15:12 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageDeleteIDView.swift
> +    func completeButtonIsAble(isAble: Bool) {
W2
속성 네이밍이랑 똑같이 isEnabled는 어떰요

2024-07-28 15:12 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageDeleteIDViewController.swift
> +    private let disposeBag = DisposeBag()
W1
disposebag는 프로퍼티로 옮겨주세오ㅛㅇ

2024-07-28 15:12 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageDeleteIDWarningViewController.swift
> +    private let dummpy = UserNovelStatusResult(interestNovelCount: 1, watchingNovelCount: 100, watchedNovelCount: 333, quitNovelCount: 29)
W1
덤피는 머여 ㅋㅋ

2024-07-28 17:33 UTC, Guryss reviewed
수고하셨습니당!

흠 저도 시뮬레이터랑 제 핸드폰으로 돌려보니까 탈퇴 사유 테이블뷰 selected가 꾹 눌러야만 되네요 ㅜㅜ 
왜 그런지 이유는 좀 더 알아봐야할 것 같습니다 ㅜㅜ

2024-07-28 17:33 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageDeleteIDView.swift
> +                .lineHeight(1.17)
W1;

옹! `lineHeight`을 1.17로 준 이유가 궁금합니다!
피그마상으론 140%가 되어있어서용!

2024-07-28 17:33 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageDeleteIDView.swift
> +            $0.applyWSSFont(.label1, with: "/80")
W1;

여기도 String 고정값이니까 따로 빼주는 게 좋을 것 같아유

2024-07-28 17:33 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageDeleteIDView.swift
> +            $0.applyWSSFont(.label1, with: "0")
밑에 bind 해주니까 지워줘두 되겠네용!

2024-07-28 17:33 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageDeleteIDViewController.swift
> +    }
W1;

여기도 마찬가지로 뷰컨 말고 뷰에서 navigationBar 설정해주며 좋을 것 같습니당

2024-07-28 17:33 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageDeleteIDViewModel.swift
> +            .observe(on: MainScheduler.instance)
W2;
해당 인풋이 메인쓰레드에서 동작해야 하는 이유가 있을까용?
여긴 구독만 해주면 되니까 굳이 메인쓰레드에서 옵져브 하지 않아도 될 것 같다는 생각이 있습니다

2024-07-28 19:55 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageDeleteIDWarningViewController.swift
> +    }
navigationItem 자체의 버튼은 View 에서 잡아주고 있어요!
그리고 효원이 코드에서 따로따로 잡아놓은 함수들을 묶어놓은 것이 preparationSetNavigationBar 함수인 것으로 알고 있숩니당~

'''
func preparationSetNavigationBar(title: String, left: UIButton?, right: UIButton?) {
        self.navigationController?.setNavigationBarHidden(false, animated: true)
        self.navigationItem.title = title
        
        if let navigationBar = self.navigationController?.navigationBar {
            let titleTextAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.Title2
            ]
            navigationBar.titleTextAttributes = titleTextAttributes
        }
        
        self.navigationItem.leftBarButtonItem = left != nil ? UIBarButtonItem(customView: left!) : nil
        self.navigationItem.rightBarButtonItem = right != nil ? UIBarButtonItem(customView: right!) : nil
    }
'''

2024-07-28 19:58 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageDeleteIDViewController.swift
> +    }
컨벤션 아니니까 W2 로 해주십셔 ><

2024-07-28 19:58 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageDeleteIDViewModel.swift
> +            .observe(on: MainScheduler.instance)
아차차 ViewModel 이었군요,,,,

2024-07-28 20:38 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageDeleteIDView.swift
> +            $0.applyWSSFont(.label1, with: "0")
무조건 첫화면에서는 0이라서 bind가 늦게 반영될 때를 대비해 넣어주어도 되지 않을까요?

2024-07-28 20:46 UTC, ena-isme commented on WSSiOS/WSSiOS/Info.plist
> -	<key>UIUserInterfaceStyle</key>
<img width="548" alt="스크린샷 2024-07-29 오전 5 46 35" src="https://github.com/user-attachments/assets/f3017c15-c67b-4058-80e8-66a41c2bf975">
이렇게 있는데 혹시 이게 아닐까요 ?

2024-08-04 16:42 UTC, hyowon612 approved these changes
엘지티티티티팉엠 👼🏻

2024-08-07 11:24 UTC, Naknakk requested changes
고생했습니다! 
VC이 너무 많아져서 확인하기가 확실히 어렵네요. 폴더링을 조금 더 깊게 해주면 좋을 것 같아요 !
그리고 씬델리게이트도 코리 다 끝나구 머지하기 전에 돌려놔주묜 . . . 조금 더 편할 것 같아요 히히

2024-08-07 11:24 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageDeleteIDViewController.swift
> +            .disposed(by: disposeBag)
W1
ViewModel에서 처리해 줘야 할 부분들이 들어간 것 같아요.
output 에 다시 accept를 해주는게 MVVM에 맞지 않는 것 같습니다

2024-08-17 13:56 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageDeleteIDView.swift
> +            $0.applyWSSFont(.label1, with: "0")
옹,,,,,, 전 개인적으로 딜레이동안 보여질 값을 0으로 두는 건 어색할 것 같단 생각입니다.
아예 안보여지거나 progressView 처럼 로딩되는 게 더 자연스러울 것 같아요. 0이면 유저가 오히려 헷갈릴 수도 있을 것 같아염. 물론 딜레이가 엄청 길진 않겠지만??? 네트워킹 통신에서 오래 걸리는 상황이라면 충분히 이런 상황이 발생할 수 있을 것 같단 생각입니당.

2024-08-17 13:59 UTC, Guryss reviewed
리뷰에 쓴 답글 확인해주심 감사하겠읍니다 ( _ _ )

2024-09-09 09:42 UTC, ena-isme commented on WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/MyPage/interest.imageset/Component 3-3.svg
뷰에 띄우면 정상적인데 컴포넌트 자체는 이렇더라구요, 디자인 쌤께 문의드렸습니다!

2024-09-09 09:59 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageDeleteIDRecordView.swift
> +            $0.contentMode = .scaleAspectFit
각각 컴포넌트들 위치 맞춰주는 것이 귀찮아서 스택뷰로 가운데 정렬 + 높이 지정 해주었숩니당

2024-09-09 10:27 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageDeleteIDViewController.swift
> +            .disposed(by: disposeBag)
output.beginEditing 부분은 ViewModel 로 수정하였습니다!
그럼 output.endEditing 부분은 output.containText.value.textIsEmpty() 를 판단하는 프로퍼티를 하나 더 만들어서 관리해야 한다는 말씀이실까요?

2024-09-09 10:30 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageDeleteIDView.swift
> +            $0.applyWSSFont(.label1, with: "0")
<img width="310" alt="스크린샷 2024-09-09 오후 7 29 36" src="https://github.com/user-attachments/assets/37fec3ea-d484-4d5d-a66e-82f24fa2ad54">

이 부분이라 우선은 서버 연결이 필요가 없겠네요! placeHolder 글자수 만큼으로 기본값 잡아놓을게요!

2024-09-09 10:32 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageDeleteIDView.swift
> +
내 욕쉼 ,,, 코리하기 불편쓰하게 해 죄송함둥

2024-09-11 15:35 UTC, Naknakk requested changes
다시 한 번 확인해주세요! 그리구 제 PR도 코리 부탁합니덩

2024-09-11 15:35 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageDeleteIDViewController.swift
> +            .disposed(by: disposeBag)
아뇹 그말이 아니라 output.containText.accept("") 나 output.tapReasonCell.accept(MyPageDeleteIDViewModel.exceptionIndexPath) 와 같이 분명 output은 구독만 해야 하는데 output에 다시 input을 accept로 넣어주고 있다는게 구조를 위반하고 있다는 말이었습니당

2024-09-13 17:51 UTC, Naknakk approved these changes
고생했습니다!

2024-09-14 15:10 UTC, Guryss approved these changes
수고하셨어용!

2024-09-17 12:10 UTC, merged