Design/#193
Team-WSS/WSS-iOS pull request #195
Opened 2024-07-26 10:22 UTC by ena-isme

### ⭐️Issue
close #
<br/>

### 🌟Motivation

<br/>

### 🌟Key Changes

<br/>

```swift
abc
```
<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-07-28 16:20 UTC, hyowon612 reviewed
고생해떠

2024-07-28 16:20 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageEditProfileViewModel.swift
> +        let isShwonWarning = PublishRelay<StringLiterals.MyPage.EditProfileWarningMessage>()
W1
shown 오타!

2024-07-28 16:20 UTC, hyowon612 commented on WSSiOS/WSSiOS/Resource/Extensions/UITextView+.swift
> +                                kerningPixel: font.kerningPixel,
💗신이나체고🥹

2024-08-07 12:08 UTC, Naknakk requested changes
뷰모델 관련 확인해주세요!~ 고생했습니당

2024-08-07 12:08 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageEditProfileViewController.swift
> +                output.introText.accept(data.intro)
W1
이부분도 뷰모델에서 처리해주는게 맞는 것 같아요! 뷰는 output을 관찰만 해야하니까요!

2024-09-13 09:51 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageEditProfileViewController.swift
> +                output.introText.accept(data.intro)
VM 에서 서버연결 함수 출력 후 구독해주는 방향으로 코드 수정하겠숩니당 ~
지금은 서버 연결 안되어 있어서 VC 에서만 코드 지워놓았어요!

2024-09-14 15:24 UTC, Guryss reviewed
KeywordLink가 사용되는 상세탐색에서 height 35입니다!
<img width="483" alt="image" src="https://github.com/user-attachments/assets/976df86c-33ba-4aa0-8bef-2bec15f3e3ec">

디자인쌤들에게 한번 여쭤보는 것이 어떨까용?!

2024-09-20 13:02 UTC, Naknakk approved these changes
고생했습니다 ~!~!

2024-09-21 09:00 UTC, Guryss requested changes
수고하셨어용 !! 리뷰 늦어저 죄송함다 ㅜㅜ 몇가지만 확인 부탁드려요오

2024-09-22 04:43 UTC, hyowon612 approved these changes
고생해씁니다

2024-09-23 05:15 UTC, ena-isme commented
@Guryss 제 환경에서는 주석처리하지 않았고 그렇게 나오지 않는데 요상하네요 ,,

2024-09-23 16:27 UTC, Guryss approved these changes
수고했지비!!!!!!!!!!!!

2024-09-25 19:22 UTC, merged