[Design&Network] #201 - 차단유저 목록 UI 구현 및 네트워크 연결
Team-WSS/WSS-iOS pull request #202
Opened 2024-08-02 09:02 UTC by ena-isme

### ⭐️Issue
close #201 
<br/>

### 🌟Motivation

<br/>

### 🌟Key Changes
토스트 메세지 applyWSSFont 적용하였습니다~!
<br/>

```swift
//In WSSToastView

func bindData(_ status: ToastStatus) {
        self.toastImageView.image = status.toastImage
        self.descriptionLabel.applyWSSFont(.body1, with: status.toastText)
        self.setLayout(status)
    }
```
<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-08-04 13:41 UTC, hyowon612 reviewed
UI랑 API를 한번에,, 짱짱 고생많았꾼
잘해써용 😛

2024-08-04 13:41 UTC, hyowon612 commented on WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
> +            static let userBlocks = "/blocks/{blockId}"
W2
```suggestion
            static func userBlocks(blockId: Int) -> String {
            return "/blocks/\(blockId)"
        }
```

요렇게 쓰면 호출할 때 쫌 더 깔꼼!

2024-08-04 13:41 UTC, hyowon612 commented on WSSiOS/WSSiOS/App/SceneDelegate.swift
> +        let navigationController = UINavigationController(rootViewController: MyPageBlockUserViewController(viewModel: MyPageBlockUserViewModel(userRepository: DefaultUserRepository(userService: Defa
W2
요건 머지할 때 원래대로 돌려주세용

2024-08-04 13:41 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Data/DTO/BlockUserResult.swift
> +struct blockList: Codable {
W1
대문자!

2024-08-04 13:41 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
> +    func deleteBlockUser(blockID: Int) -> Observable<Void>
W2
어떤건 blockID이고, blockId 인데
우리 컨벤션에 기반하면 blockID가 맞네용..(나도 몰라서 찾아보고 옴)
blockID로 통일하는 게 좋을듯!

2024-08-04 13:41 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
> +        return Observable.just("shinjiwonZZang")
신지원짱ㅋㅋ

2024-08-04 13:41 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageBlockUserTableViewCell.swift
> +                         unblockButton)
W1
cell은 contentView에 addSubView하기 꼭‼️
아마 이거땜에 셀 셀렉이 안됐을거예용

2024-08-04 13:41 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageBlockUserViewController.swift
> +    private let unblockButtonTapReleay = PublishRelay<IndexPath>()
W1
relay 오타!

2024-08-04 13:41 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageBlockUserViewModel.swift
> +        let showToastMessage: PublishRelay<String>
W2
타입이 스트링이니  (예를 들어)  `toastMessageText` 와 같은 변수명으로 지으면 좋을 거 같아용 
`showToastMessage`는 먼가 boolean 타입의 변수인 느낌이 있네여

2024-08-07 12:54 UTC, Naknakk requested changes
고생했습니다!
혹시 차단목록 구분선이 안보이는데, 사진에서만 안보이는 거겠죵?!

2024-08-07 12:54 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageBlockUserView.swift
> +        }
W1
뒤로가기 버튼이 너무 안쪽으로 밀려서 나타나는 것 같은데, size를 터치영역이 아니라 이미지 크기인 24로 잡아주는게 어떨까요?

2024-08-17 14:50 UTC, Guryss reviewed
수고많으셨습니다!

하나 제안드리고 싶은 부분이 있는데, 현재 Presentation > MyPage 폴더 내에 많은 뷰 관련 파일들이 있어서 찾아보기가 좀 힘든 면이 있어서요!

**차단, 회원탈퇴, 프로필 수정 등 한번 더 폴더링을 해서 정리하면 좋을 같습니다!**

2024-08-17 14:50 UTC, Guryss commented on WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/MyPage/imgEmptyCat.imageset/imgEmptyCat.svg
W2; 
고양이 이미지는 png로 빼는 게 어떨까요?
이정도의 단순하지 않은? 복잡한 이미지는 Png로 3배수 뽑는 게 좋을 것 같단 생각 ..

2024-08-17 14:50 UTC, Guryss commented on WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/MyPage/imgProfile.imageset/imgProfile.svg
W2;
이것두 마찬가지 입니다!

2024-08-17 14:50 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
> +        return Observable.just("shinjiwonZZang")
zizoneZZang

2024-08-17 14:50 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageBlockUserView.swift
> +    }
W1;
tintColor Gray300으로 잡아주세용!

2024-08-17 14:50 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageBlockUserTableViewCell.swift
> +import RxSwift
W1;

Rx가 쓰이는 코드가 없어보여서 import 안해도 될 것 같아용

2024-09-09 13:28 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageBlockUserTableViewCell.swift
> +import RxSwift
VC 에서 잡아주고 있숩니당!

```
output.bindCell
            .bind(to: rootView.blockTableView.rx.items(cellIdentifier: MyPageBlockUserTableViewCell.cellIdentifier, cellType: MyPageBlockUserTableViewCell.self)) { row, data, cell in
                cell.unblockButton.rx.tap
                    .map { IndexPath(row: row, section: 0) }
                    .subscribe(onNext: { indexPath in
                        self.unblockButtonTapRelay.accept(indexPath)
                    })
                    .disposed(by: cell.disposeBag)
                
                cell.bindData(image: data.avatarImage, nickname: data.nickname)
            }
            .disposed(by: disposeBag)
```

이게 Cell 안에 있는 버튼을 구독해주는 거라 이렇게 구현했는데요 ,,,
굳이 왜 이렇게 해야 하냐 ! 에 대한 당시의 저의 생각은
그냥 인덱스나 string 에 대한 정보만 넘기도록 하면, 다시 차단 list 에서 해당 index 를 찾아 blockID 를 넘기는 프로퍼티를 하나 더 만들어야 하는데 뭔가 이게 더 간단해 보여서 이렇게 했숨당~ 
편하게 의견 말씀해주세영

2024-09-09 13:42 UTC, ena-isme commented
@Naknakk 구분선 여부는 더미데이터 넣어달라고 요청한 뒤 다시 체크해볼게요!
@Guryss 폴더 파일은 현재 열려있는 세개의 PR 까지만 머지하고 다시 이슈 파도록 하겠숩니당 ㅠㅅㅠ 코리할 때 불편드려 쏘리 베리 마치

2024-09-11 15:40 UTC, Naknakk requested changes
수정하느라 고생했습니당. 그리고 구분선 이슈는 확인하고 말해준다고 했는데, 잘 나타나는걸로 체크된 걸까요? 아니면 꼭 서버 더미데이터가 아니더라도 직접 더미데이터 만들어서 확인해도 좋을 것 같아요

2024-09-11 15:40 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Data/DTO/BlockUserResult.swift
> +struct BlockList: Codable {
W1
구조체명은 BlockUser 정도가 좋지 않을까요? List가 네이밍에 들어가는건 좋지 않은 것 같아요

2024-09-13 09:21 UTC, ena-isme commented
@Naknakk 구분선 확인했숨니당~

2024-09-13 17:53 UTC, Naknakk approved these changes
고생했습니다 !

2024-09-14 15:16 UTC, Guryss reviewed
리뷰 하나만 확인 부탁드려용!

2024-09-14 15:16 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageBlockUserTableViewCell.swift
> +import RxSwift
이 부분은 어떻게 되었을까용??

2024-09-14 15:22 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageBlockUserTableViewCell.swift
> +import RxSwift
Cell 에서 disposebag 을 부르고 있어서 필요할 것 같아요 ㅠ 개선방안 찾아보고 최대한 해결해볼게요 !

2024-09-17 14:03 UTC, hyowon612 approved these changes
엘지티엠

2024-09-18 12:01 UTC, merged