[Network] #219 - SosoPick 조회 및 일반탐색 API 연결
Team-WSS/WSS-iOS pull request #229
Opened 2024-09-17 10:30 UTC by Guryss

### ⭐️Issue
close #219 
<br/>

### 🌟Motivation
- 소소픽 조회 API 연결 했습니다. 
- 일반탐색 API 연결 했습니다. 
<br/>

### 🌟Key Changes

<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-09-18 04:15 UTC, hyowon612 approved these changes
천재만재걸이네요 짱짱
피알도 이렇게 이쁘게 올려주다니 ㄷㄷ
나도 일반탐색 API 써야하는데 열심히 쇽샥 하겠음 ㅋㅎㅋㅎ. 🤍
고생 많았어요 ~~~

2024-09-18 04:15 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewController/NormalSearchViewController.swift
> +            .disposed(by: disposeBag)
W2
하나로 합칠 수 이써요
글고 얘네도 뷰모델로 빼면 좋을 거 같아요!
```suggestion
        rootView.resultView.normalSearchCollectionView.rx.swipeGesture([.up, .down])
            .when(.recognized)
            .subscribe(with: self, onNext: { owner, _ in
                self.view.endEditing(true)
            })
            .disposed(by: disposeBag)
```

2024-09-18 04:15 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
>          let inquiryButtonEnabled: Observable<Void>
W2
input으로 들어온 버튼 이벤트 자체를 바로 내보내는 형태인 거 같은데
output에는 해당 이벤트로 인해 발생하는 구체적인 행동을 명시해주면 더 좋을 거 같아요!
예를 들면 `scrollToTop`, `endEditing` 처럼요!

2024-09-18 04:15 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/Search/Search/SearchViewController/SearchViewController.swift
> +
W2
줄바꿈 없애주세영

2024-09-18 06:36 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
>          let inquiryButtonEnabled: Observable<Void>
이전에 컨벤션으로 버튼 이벤트의 인풋, 아웃풋의 네이밍을 정했어서 그걸 따랐던거긴 한데 ..
오늘 회의에서 얘기해보는 건 어떨지?!

2024-09-18 07:04 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewController/NormalSearchViewController.swift
> +            .disposed(by: disposeBag)
뷰모델로 분리 했습니당! 감사해용

2024-09-18 17:05 UTC, Guryss commented
**TODO: 일반탐색 내 검색어 30자 제한 기능 추가하기**

2024-09-19 05:04 UTC, ena-isme reviewed
뽀뽀 쪽

2024-09-19 05:04 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
> +                    })
W1
우리 ViewModel 에서 API 호출할 때 따로 함수 만들어서 했던 걸로 기억하는데 바로 해준 이유가 있을까요 ?
에러처리도 되지 않고 있는 것으로 보여용 ~!

2024-09-19 05:09 UTC, Guryss commented on WSSiOS/WSSiOS.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 9SVDHQS4M3;
이것은 개인 핸드폰으로 빌드할 때 Developer Team을 저로 설정하면서 고유 코드가 변경된 것 같아요! 크게 상관 없을 겁니다 😃

2024-09-19 17:22 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
> +                    })
한줄이라서 함수를 따로 만들진 않았는데 함수로 빼서 만들겠습니다! 컨벤션이었네요 🥲🥲
에러처리 넣어서 수정하겠습니다~

2024-09-20 09:42 UTC, ena-isme approved these changes
GOOD

2024-09-20 09:42 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
> +    private func getNormalSearchList(query: String, page: Int) -> Observable<NormalSearchNovels>{
W2 
'Observable<NormalSearchNovels>{' => 'Observable<NormalSearchNovels> {'
로 한칸 띄워주깅~

2024-09-20 09:42 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
> +            .do(onNext: { data in
한 번만 방출하면 되니까 do ? Good

2024-09-20 15:04 UTC, Naknakk requested changes
너무 고생했습니다!! 진짜 숙원의 무한 스크롤을 드디어 . . . 대단하네요 !~!~!~!!!!
백버튼 관련해서 한번만 확인해 주세요!

2024-09-20 15:04 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
> +            .map { _ in () }
W3
컬렉션뷰 스와이프 하면 키보드 내리는 디테일 . . 최고입니다

2024-09-21 06:31 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
> +            .map { _ in () }
이거슨 .. 효원이꺼 델고와썽요

2024-09-21 06:34 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewController/NormalSearchViewController.swift
> +            .disposed(by: disposeBag)
꼼꼼한 코리 감사합니당 수정할게요!

2024-09-21 06:44 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewController/NormalSearchViewController.swift
> +        let checkNearBottomEdge = self.rootView.resultView.scrollView.contentOffset.y + self.rootView.resultView.scrollView.bounds.size.height + 1.0 >= self.rootView.resultView.scrollView.contentSize
`self.rootView.resultView.scrollView.contentOffset.y` : 스크롤 뷰의 위쪽에서 얼마나 스크롤했는지에 대한 y 좌표 값
`self.rootView.resultView.scrollView.bounds.size.height` : 스크롤 뷰의 현재 화면에 보여지는 높이
`self.rootView.resultView.scrollView.contentSize.height` : 스크롤 가능한 전체 영역의 높이

즉 사용자의 스크롤 위치 + 스크롤뷰의 현재 높이 + 1.0 >= 스크롤 가능한 전체 영역의 높이 로 이해해주심 됩니다.
1.0은 스크롤이 바닥에 닿았을 때를 조금 더 먼저 인식하는 게 좋을 것 같아 임의로 더한 값입니다. ㅎㅅㅎ

2024-09-22 05:35 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewController/NormalSearchViewController.swift
> +        let checkNearBottomEdge = self.rootView.resultView.scrollView.contentOffset.y + self.rootView.resultView.scrollView.bounds.size.height + 1.0 >= self.rootView.resultView.scrollView.contentSize
아하 이제 이해했습니다 !! 꼼꼼한 설명 너무 고마워요! 
사용자의 현재 스크롤 위치는 스크롤 가장 위쪽을 알려주니까.. 여기에 현재 스크롤뷰 높이를 더해줘야 가장 아래쪽의 값이 나오겠군요 좋습니당!

2024-09-22 05:37 UTC, Naknakk approved these changes
고생했습니다 무한스크롤 짱짱!!

2024-09-22 07:22 UTC, merged