[Design&Network] #164 - HomeView 지금 뜨는 수다글 UI 및 조회 API 연결
Team-WSS/WSS-iOS pull request #232
Opened 2024-09-18 11:47 UTC by Guryss

### ⭐️Issue
close #164 
<br/>

### 🌟Motivation
- 지금 뜨는 수다글 UI 및 조회 API 연결 구현 했습니다. 
<br/>

### 🌟Key Changes

<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-09-19 05:12 UTC, ena-isme reviewed
VC, VM 은 추가로 코리 달게요!

2024-09-19 05:12 UTC, ena-isme commented on WSSiOS/WSSiOS.xcodeproj/project.pbxproj
> +		2CA2F64E2B527B060045B4C2 /* MyPageCustomModalView.swift in Sources */ = {isa = PBXBuildFile; fileRef = 2CA2F64D2B527B060045B4C2 /* MyPageCustomModalView.swift */; };
이거 내 뷰인데 머지할 때 없애주세요 ~ 
main 에는 없어져 있습니당

2024-09-19 05:12 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
> +            $0.contentInsetAdjustmentBehavior = .never
W2
contentInsetAdjustmentBehavior  를 never 로 준 것은 safeLayout 을 고려하지 않는다는 건가요 ?

2024-09-19 18:02 UTC, Guryss commented on WSSiOS/WSSiOS.xcodeproj/project.pbxproj
> +		2CA2F64E2B527B060045B4C2 /* MyPageCustomModalView.swift in Sources */ = {isa = PBXBuildFile; fileRef = 2CA2F64D2B527B060045B4C2 /* MyPageCustomModalView.swift */; };
헙 저거만 찾아서 없애기 어려우니까 .. 일단 두고 추후에 수정하는 건 어떨까여. 컨플릭 날까봐 수동으로 건들이기 무서움 ,,..

2024-09-19 18:05 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
> +            $0.contentInsetAdjustmentBehavior = .never
네네! 캐러셀뷰이다보니까 inset이 고려된 채로 스크롤이 되면 어색하다는 판단이었습니다. safeAreaLayout에서 제공하는 Inset 범위를 무시하고 스크롤이 되어야 넘겨진 뷰가 자연스럽게 넘어가지더라구요!

2024-09-20 06:53 UTC, hyowon612 reviewed
고생했씁니당!!

한가지 의문점이 있는데
<img width="355" alt="image" src="https://github.com/user-attachments/assets/5f7613a8-53a1-4749-b019-eab054df7285">
위의 이미지처럼 오늘의 인기작과 다르게
<img width="349" alt="image" src="https://github.com/user-attachments/assets/1a224bf4-0c90-49c0-be5b-1724d99b19a1">
지금 뜨는 수다글 뷰는
오른쪽에 다음 셀이 빼꼼 보이는 뷰가 아닙니다.

그래서 제 생각엔 박스 자체가 스크롤되어서 넘어가는 형태가 아닌
박스 내의 텍스트만 스크롤되는 형태라고 보여지는데

디쌤들한테 한번 확인해봐야 할 것 같습니당

(+ 궁금해서 안드 피알도 확인해봤는데 내가 말한 형태로 구현했더라구요)

2024-09-20 09:48 UTC, ena-isme reviewed
화이팅

2024-09-20 09:48 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
> +
W1
delegate 말고 rx.setDelegate 쓰는 건 어떨까요 ?
고냥 Delegate 사용하게 되면 controlEvent 가 작동되지 않다구 해용!

2024-09-20 15:48 UTC, Naknakk requested changes
들여쓰기 하나만 수정해주세요! 고생했습니다.
만약 캐러셀 뷰가 옆에 빼꼼 안보이는 걸로 수정해야 한다면, 저는 효원이 말대로 텍스트만 스크롤 돼서 넘어오는 것 보다는 박스 째로 스크롤 돼서 페이지가 넘어가는게 더 자연스러운 것 같아요 ..! 안드는 텍스트만 스크롤 되지만 보고 왔는데 어색한 느낌 ...!!

만약 박스 째로 스크롤 하고, 옆에 뷰가 빼꼼 하고 있지 않다면 페이징 기능을 isPagingEnabled = true로 해서도 구현 가능할지도 ㅎ.ㅎ.ㅎ...

2024-09-20 15:48 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
> +            $0.decelerationRate = .fast
W3
오호.. 요걸로 스크롤 감속을 빠르게 해서 캐러셀 만드는데 썼군용 ..좋네요. 아니면 한번에 여러 페이지가 넘어갈 수도 있을테니 ...!

2024-09-20 15:48 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
> +        DispatchQueue.main.async {
W3
오홍.. DispatchQueue가 쓰였구뇽 어떤 이유에서 쓰인건지 궁금해요!

2024-09-20 15:48 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
> +        }
W3
오늘 보여준 것처럼 애니메이션을 넣으려면 제 227 브랜치처럼 인디케이터를 뷰로 구현해야할거에용!

2024-09-20 15:48 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeRealtimePopularCollectionViewCell.swift
W2
StackView를 썼으면 좀 더 레이아웃 잡는게 간단했을 것 같아용!

2024-09-20 15:48 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeRealtimePopularCollectionViewCell.swift
> +        thirdFeedView.bindData(data: data[2])
W2
데이터가 3의 배수 외에 7개 이렇게 들어오는 경우는 없는거죵?.? 이렇게 되면 들어온 데이터가 3의 배수가 아닐 때 터질 것 같아서용!

2024-09-20 15:48 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
> +            output.realtimePopularData
W1
들여쓰기가 수정되어야 할 것 같아용!

2024-09-20 15:48 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
> +        output.announcemnetButtonEnabled
W3
네이밍 회의에서 input에 따른 최종적인 행동을 명시하자구 해서 navigateToAnnouncementView가 더 좋은 것 같아요!

2024-09-20 15:48 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
> +
W3
짱이네요  진짜 페이징 기능을 직접 만들었군요..

2024-09-21 06:58 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
> +
오웅 고마워요! 수정하겠습니다 >3<

2024-09-21 07:12 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeRealtimePopularCollectionViewCell.swift
> +        thirdFeedView.bindData(data: data[2])
지금 서버에선 8개가 들어와서 guard return 코드 넣어주긴 했어요!
근데 저번에 듣기론 배포할 땐 9개 무조건 들어가 있다구 해서 ... 괜찮을듯?!

2024-09-21 07:16 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
> +        }
확인해볼게요오~

2024-09-21 07:18 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
> +        DispatchQueue.main.async {
`configureDots`함수가 보면 snp로 레이아웃을 반영해주는 코드가 들어가있잖아요?!
근데 해당 함수 호출되는 위치는 뷰컨트롤러에 리스트 데이터와 바인딩 할 때 리스트 내 객체 개수를 받아오면서 호출이 되고 있어요! 
그래서 DispatchQueue.main.async 블럭을 추가해주었습니다.!

2024-09-21 07:20 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
> +        DispatchQueue.main.async {
근데 생각해보니까 bind 코드 위에 observe(on: MainScheduler.instance) 호출해주는거랑 똑같네요?!?!?
이거 바보 이슈다  깔깔깔 
수정해둘게요 ㅎㅎ

2024-09-21 08:35 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeRealtimePopularCollectionViewCell.swift
Stackview로 수정해두었습니당 ㅎㅎ 감사해용

2024-09-22 05:02 UTC, hyowon612 approved these changes
엘지티엠!

2024-09-22 05:27 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
> +        DispatchQueue.main.async {
ㅋㅋㅋㅋㅋ좋아요

2024-09-22 05:28 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
> +        }
요거는 적용 해볼 예정인가용? 아니면 일단 머지할 예정인가용?

2024-09-22 05:32 UTC, Naknakk approved these changes
고생했습니다 짱짱! 레이아웃 변경도 순식간에 되게 잘했네용..

2024-09-22 07:27 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
> +            .map { $0.compactMap { $0 } }
그렇네용! 이전에 realtimePopularData을 옵셔널하게 처리해놔서 넣어놨던 것 같습니당.
수정할게요!

2024-09-22 07:42 UTC, merged