Feat/#233
Team-WSS/WSS-iOS pull request #235
Opened 2024-09-18 16:29 UTC by ena-isme

### ⭐️Issue
close #233 
<br/>

### 🌟Motivation

<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

토큰 문제로 서버 연결을 확인 못함
완료했을 때 정책이 모호
위와 같은 이유로 Draft 입니다

++ 브런치 잘못파서 옮겨놓느라,,, 커밋이 뭉텅입니다 ,,,
<br/>

2024-09-28 03:09 UTC, hyowon612 approved these changes
엘지티엠 고생했어요

2024-09-28 03:09 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageProfileVisibilityViewController.swift
> +
개행 삭제

2024-09-28 03:09 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageProfileVisibilityViewModel.swift
> +        print(self.isPublic, "💖")
프린트문 삭제

2024-09-28 04:01 UTC, Guryss approved these changes

2024-09-30 17:50 UTC, Naknakk requested changes
고생했습니다! 코드리뷰 읽어주세용!

2024-09-30 17:50 UTC, Naknakk commented on WSSiOS/WSSiOS/App/SceneDelegate.swift
> +        let navigationController = UINavigationController(rootViewController: MyPageSettingViewController())
W3
메인 당겨와서 브랜치 최신화 할 때 까먹지말기~~

2024-09-30 17:50 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageProfileVisibilityView.swift
> +            $0.leading.equalToSuperview().inset(30)
W1
20인 것 같습니당

2024-09-30 17:50 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageProfileVisibilityView.swift
> +        }
W1
이 버튼도 터치영역 잡아주기 보다는 없이 가도 좋을 것 같아요.
피그마에 비해 완료 버튼이 안쪽으로 밀려들어가 있는게 보여서요! 아래 체크 동그라미가 완 글자 밑에 있어야 하는데 밀려서 완료 글자 중간에 위치하게 된 것 같습니당.

2024-09-30 17:50 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageProfileVisibilityViewModel.swift
> +            .disposed(by: disposeBag)
W1
subscribe 안에 또 subscribe가 있는게 좋지 않은 것 같습니다. 그럼 해당 이벤트가 일어날 때마다 매번 내부에서는 새로운 구독이 추가되는건데, 메모리 측면에서 좋지 않은 것 같아요. 의도치 않은 동작을 만들 수도 있을 것 같구요.
flatmapLastest를 추가해서 여기서 작동시키는게 좋을 것 같습니다.

2024-09-30 17:50 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageProfileVisibilityViewModel.swift
> +        print(self.isPublic, "💖")
W1
초기값을 init에서 굳이 실행할 필요가 없는 것 같아요 ! transform 메서드가 VC의 viewDidLoad에서 작동하니, transform 메서드 내에 넣어주면 더 일괄적이고 좋을 것 같습니다.

2024-11-15 19:18 UTC, closed without merging