[Design] #211 - 작품평가 UI 1차 구현
Team-WSS/WSS-iOS pull request #238
Opened 2024-09-19 02:51 UTC by hyowon612

### ⭐️Issue
close #
<br/>

### 🌟Motivation

<br/>

### 🌟Key Changes

<br/>

```swift
abc
```
<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-09-20 05:33 UTC, ena-isme commented
여러분 전효원이 2224 줄의 코리를 우리에게 던졌습니다

2024-09-23 04:55 UTC, ena-isme reviewed
아이궁 수고하셨쑵니다 💖

2024-09-23 04:55 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelKeywordSelectModalView.swift
> +            $0.size.equalTo(25)
W1
버튼 이미지 자체는 25인데 터치영역은 65 인것 같아요!

2024-09-23 04:55 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelKeywordSelectSearchBarView.swift
> +            $0.rightView = UIView(frame: CGRect(x: 0.0, y: 0.0, width: 82.0, height: 0.0))
W2
이 부분 width 가 82 일까요 ?!

2024-09-23 04:55 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelKeywordSelectSearchResultView.swift
> +            layout.minimumLineSpacing = 8
W2
한 줄로 스크롤 되는 것 같은데 linespacing 을 준 이유가 있을까요 ?

2024-09-23 04:55 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelReviewAttractivePointView.swift
> +}
W1
StringLIterals GOGO

2024-09-23 04:55 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelReviewKeywordView.swift
> +        }
W2
SearchView 자체를 탭할 때 모달로 넘어가는 로직맞나요?
그렇다면 searchButton 자체가 private 로 설정되어있기도 하고, 다시 isEnabled 처리하지 않아 보이는데 ImageView 로 처리하는 건 어떨까요 ?

2024-09-23 04:55 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewController/NovelKeywordSelectModalViewController.swift
> +            updatedEnteredText: rootView.novelKeywordSelectSearchBarView.keywordTextField.rx.text.orEmpty.distinctUntilChanged().asObservable(),
W3
.distinctUntilChanged() 굳

2024-09-23 04:55 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewController/NovelKeywordSelectModalViewController.swift
> +        output.selectedKeywordListData.bind(to: rootView.novelSelectedKeywordListView.selectedKeywordCollectionView.rx.items(cellIdentifier: NovelSelectedKeywordCollectionViewCell.cellIdentifier, cel
W1
.bind 아래로 보내주세요~!

2024-09-23 04:55 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewController/NovelKeywordSelectModalViewController.swift
> +        output.keywordSearchResultListData.bind(to: rootView.novelKeywordSelectSearchResultView.searchResultCollectionView.rx.items(cellIdentifier: NovelKeywordSelectSearchResultCollectionViewCell.ce
W1
여기도 한줄 내려주기

2024-09-23 04:55 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewController/NovelReviewViewController.swift
> +            novelReviewKeywordSelectedNotification: NotificationCenter.default.rx.notification(Notification.Name("NovelReviewKeywordSelected")).asObservable()
W3
전효원 특기 나왔네

2024-09-24 01:47 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelKeywordSelectSearchBarView.swift
> +            $0.rightView = UIView(frame: CGRect(x: 0.0, y: 0.0, width: 82.0, height: 0.0))
네네
![image](https://github.com/user-attachments/assets/081ada3f-4ca4-4ff1-91d0-24d2fcb9d1b3)
여기 버튼 영역 빼준겁니당

2024-09-24 01:49 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelKeywordSelectSearchResultView.swift
> +            layout.minimumLineSpacing = 8
![CleanShot 2024-09-24 at 10 49 10](https://github.com/user-attachments/assets/8edba59d-c64c-40ea-9af5-51daba0cceb1)
한줄 스크롤 아닙니당!!

2024-09-24 01:51 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelReviewKeywordView.swift
> +        }
그러네요!!

2024-09-24 01:55 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewController/NovelReviewViewController.swift
> +            novelReviewKeywordSelectedNotification: NotificationCenter.default.rx.notification(Notification.Name("NovelReviewKeywordSelected")).asObservable()
줄 수 있는게,,, 노티피케이션 바께 업따...

2024-09-24 01:57 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelReviewAttractivePointView.swift
> +}
Data폴더에 파일 따로 빼주었어여

2024-09-25 05:02 UTC, Guryss reviewed
수고하셨으요~~~~~~~ 최고당

추후 제가 만들어둔 키워드뷰 붙이면 될듯! 전 당신이 만든 키워드 검색뷰를 붙이겠어요..

2024-09-25 05:02 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewController/NovelReviewViewController.swift
> +        } else if collectionView.tag == 2 {
ㅁㅊ! 여기서 tag로 분기처리 하는거군아!!!!!!
나는 그냥 다 호출했엇는데 .......................... 똑쟁이군요

2024-09-25 05:22 UTC, ena-isme approved these changes
화긴! 굳

2024-09-25 05:35 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewController/NovelReviewViewController.swift
> +        } else if collectionView.tag == 2 {
해놓고 보니까 태그가 전혀 직관적이지 않은거 같아서
태그 안쓰고 분기처리 하는걸로 바꿨어여~!

2024-09-25 06:19 UTC, Guryss approved these changes
수고했네~~~

2024-09-25 09:23 UTC, Naknakk requested changes
진짜 짱이다 . . 고생했습니다. 컬렉션뷰가 잔뜩인데 진짜 잘 처리했네요 ..!! 데이터 바로 노티피케이션 센터로 넘겨주는 것도 좋네요!! 많이 배워갑니다!

2024-09-25 15:23 UTC, hyowon612 commented on WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/NovelReview/icNovelReviewQuit.imageset/Status=icTagStop.png
조은생각

2024-09-26 04:36 UTC, hyowon612 commented on WSSiOS/WSSiOS/Resource/Extensions/UIButton+.swift
> +
이 extension은 이제 안 쓸 예정이라 UILabel extension으로 새로 구현했습니다!

2024-09-26 04:38 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Data/Base/AttractivePoints.swift
나중에 하나로 정리합시당

2024-09-26 04:38 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/Base/CenterAlignedCollectionViewFlowLayout.swift
땡스투지피티

2024-09-26 04:40 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelKeywordSelectSearchBarView.swift
피그마 따라가는게 맞지 않을까요?

2024-09-26 05:34 UTC, Naknakk commented on WSSiOS/WSSiOS/Resource/Extensions/UIButton+.swift
> +
짱이네요

2024-09-26 05:35 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Data/Base/AttractivePoints.swift
나중에 그럼 제가 합칠 때 제 파일을 이걸로 통합할게요~~

2024-09-26 05:37 UTC, Naknakk approved these changes
고생했습니다 짱짱빠르다~~

X버튼 생기는 유무는 QA때 할 질문으로 일단 미뤄둬도 될 것 같아요.
저는 일단 iOS에서 주는 일반적인 경험을 따라가는게 좋다구 생각합니다..! 실제로 글씨가 없을 때는 필요없는 버튼이기도 하니까요!

2024-09-26 05:49 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelKeywordSelectSearchBarView.swift
디쌤께 한번 여쭤볼게요!! 빠른 작업 위해 일단 머지하겠슴다

2024-09-26 05:49 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelKeywordSelectSearchBarView.swift
디쌤께 한번 여쭤볼게요!! 빠른 작업 위해 일단 머지하겠슴다

2024-09-26 06:11 UTC, merged