[Design] #241 -
Team-WSS/WSS-iOS pull request #242
Opened 2024-09-21 09:06 UTC by ena-isme

### ⭐️Issue
close #
<br/>

### 🌟Motivation

<br/>

### 🌟Key Changes

<br/>

```swift
abc
```
<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-09-22 11:29 UTC, Guryss requested changes
수고하셨어요~ 화이티이이잉 리뷰 확인 부탁드립니두

2024-09-22 11:29 UTC, Guryss commented on WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
> +        static let afterDelete = userBasePath + "추후 삭제"
W2;
이 친구는 왜 들어간건지 알 수 있을까요?!

2024-09-22 11:29 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageChangeUserInfoView.swift
> +            }
W1;
드롭다운에 쓰이는 쉐브론이랑 다른 이미지 같아요! 따로 추출해서 사용하는 게 좋을 것 같슴다
사이즈가 달라요!

2024-09-22 11:29 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageChangeUserInfoView.swift
> +            $0.setTitleColor(.wssGray200, for: .normal)
W1;
완료 버튼 활성화 안되어있을때의 디자인이 따로 나왔을까요?! 
피그마에 찾아보는데 잘 안보이네요 ㅜㅜ 텍스트컬러는 따로 논의가 된 부분일까요?

2024-09-22 11:29 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageChangeUserInfoView.swift
> +                $0.trailing.equalToSuperview().inset(13.5)
W1;
trailing 20인 것 같아요!

2024-09-22 11:29 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageChangeUserInfoView.swift
> +            $0.layer.borderColor = select ? UIColor.wssPrimary50.cgColor : UIColor.clear.cgColor
W1;
selected 되었을 때 border 컬러가 primary100 입니당.
클릭하니까 border가 안보였던 이유인듯!

2024-09-22 11:29 UTC, Guryss commented on WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
> +            static let myPageChangeUserInfo = "성별/나이 변경"
W1;
참고로 계정정보 페이지의 navigationBar 타이틀이 변경되었어요!
계정설정 -> 계정정보

2024-09-22 11:29 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageSettingView.swift
> +        }
W1;
size 44로 통일하는 게 좋을 것 같네용

2024-09-22 11:29 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageInfoViewController.swift
> +    private let updateDataRelay = BehaviorRelay(value: false)
```suggestion
    private let updateDataRelay = BehaviorRelay<Bool>(value: false)
```

2024-09-22 11:29 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageInfoViewModel.swift
> +        let bindEmail = BehaviorRelay(value: "")
```suggestion
        let bindEmail = BehaviorRelay<String>(value: "")
```

2024-09-22 11:29 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageDeleteIDView.swift
> +        }
여기도 size 44로 !

2024-09-22 11:29 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageChangeUserInfoViewModel.swift
> +                            output.popViewConroller.accept(true)
W2;
개행 없애주세용

2024-09-22 11:40 UTC, ena-isme commented on WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
> +        static let afterDelete = userBasePath + "추후 삭제"
앱잼때 쓰던 url 이랑 주소가 겹쳐서 추후 관련 코드를 삭제하고자 함입니당

2024-09-22 11:41 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageChangeUserInfoView.swift
> +            $0.setTitleColor(.wssGray200, for: .normal)
마이페이지 모든 완료 버튼은 유저 닉네임 변경 뷰와 동일하게 해달라는 요청입니당 ~

2024-09-22 11:42 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageChangeUserInfoView.swift
> +            $0.layer.borderColor = select ? UIColor.wssPrimary50.cgColor : UIColor.clear.cgColor
꼼꼼왕 감삼둥

2024-09-23 16:30 UTC, Guryss approved these changes
빠른 피드백 반영 수고많았다면서...... 좀만 더 해보자면쒀....... 고생많다면쒀.....♡

2024-09-24 01:24 UTC, hyowon612 approved these changes
고생해씁니다아아

2024-09-24 01:24 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageInfoViewController.swift
>  import RxRelay
W2
RxCocoa말고 RxRelay 임포트해준 이유 있나요?

2024-09-24 01:24 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageChangeUserInfoViewModel.swift
> +        let popViewConroller = PublishRelay<Bool>()
W2
Controller 오타!
true만 넘겨주고 있어서 Void 타입으로 선언해도 될듯!

2024-09-24 11:17 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageInfoViewController.swift
>  import RxRelay
RxCocoa 내부에 RxRelay 가 포함되어 있는데,
rxreleay 외에 ControlEvent 나 drive 같은 요소를 사용하지 않았기 때문에 릴레이만 추가해주었숩니당!

2024-09-25 05:24 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageChangeUserInfoViewController.swift
> +            birthViewTapped: rootView.birthButtonView.rx.tapGesture(),
안에 이미지도 있고, 텍스트도 있어서 버튼이 아닌 뷰로 만들었습니다!
큰 의미는 없습니다!

2024-09-25 10:25 UTC, ena-isme commented on WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageChangeUserInfoView.swift
> +        }
이거 오늘 상의해봅시둥

2024-09-25 19:34 UTC, merged