[Design] #211 - 작품평가 UI 2차 구현
Team-WSS/WSS-iOS pull request #258
Opened 2024-09-26 06:14 UTC by hyowon612

### ⭐️Issue
close #
<br/>

### 🌟Motivation

<br/>

### 🌟Key Changes

<br/>

```swift
abc
```
<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-09-26 17:11 UTC, Naknakk requested changes
고생했습니다! 진짜 깔끔하게 날짜선택 모달이 구현되었네요.. 아주 멋집니다용..
봤어요 상황에서 시작&종료날짜 선택 버튼에 대한 피드백도 한번 읽어봐 주세요!

2024-09-26 17:11 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelDateSelectModalDateButtonView.swift
> +        endDateLabel.textColor = isStartDateSelected ? .wssGray200 : .black
W1
그냥 블랙 말구 wssBlack을 사용해야 할 것 같습니당!

2024-09-26 17:12 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelDateSelectModalTitleView.swift
> +            $0.applyWSSFont(.title1, with: title)
W1
TitleLabel 색도 wssBlack으로 지정해줘야 할 것 같아용!

2024-09-26 17:23 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewModel/NovelDateSelectModalViewModel.swift
W1
예전에는 종료 날짜를 시작 날짜보다 더 이전 날짜로 설정한다면, 시작 날짜가 종료 날짜를 따라가도록 했었는데 지금은 시작 날짜보다 더 이전 날짜로 절대 설정할 수 없게 되어 있잖아용 ?! 처음 봤을 때는 보통 시작 날짜부터 정하니 괜찮은 흐름이다 싶었는데요, 사용해보니 문제가 있는 것 같습니다!

오늘 날짜가 24.09.27이라 두면,
1. 시작 날짜를 23.09.28로 설정한다.
2. 종료 날짜를 설정하기 위해 버튼을 탭한다. 종료 날짜는 기본적으로 24.09.27로 오늘 날짜로 초기화 되어있다.
3. 이제 어떻게 해도 종료 날짜를 23년대로 넘길 수가 없다 . . . 아무리 작게 해봐도 2024.01.01보다 더 이전의 날짜를 선택할 수 없다.

입니다..!! 그래서 제 생각에는 종료 날짜를 시작 날짜보다 더 이전 날짜로 설정한다면, 예전 방식대로 시작 날짜를 종료 날짜에 맞추는 방식으로 하는게 맞는 것 같아요!

2024-09-26 18:43 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewModel/NovelDateSelectModalViewModel.swift
이 부분은 기획측 요청입니다!!

2024-09-26 18:44 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewModel/NovelDateSelectModalViewModel.swift
<img width="470" alt="image" src="https://github.com/user-attachments/assets/63d822d2-d5c3-49a2-9fe2-b38da5fe527d">

이 부분은 기획측 요청입니다!!

2024-09-26 18:55 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelReviewAssistantView/NovelDateSelectModalDateButtonView.swift
헉 그렇군요 확인했습니다!! 곰마워요

2024-09-27 04:25 UTC, Guryss approved these changes
수고했어용 리뷰 하나만 반영해주면 될듯!

2024-09-27 04:25 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewView/NovelDateSelectModalView.swift
> +            $0.setImage(.icCacelModal, for: .normal)
W1;
이거 일단 main pull 받고 머지해서 수정해야할듯요

2024-09-27 05:28 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewModel/NovelDateSelectModalViewModel.swift
기획측 요청이긴 한데, 실 사용에 너무 불편한 점이 많을 것 같아서 바꾸는걸 제안해보는건 어떨까요..?

2024-09-27 05:34 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewModel/NovelDateSelectModalViewModel.swift
내일 qa에서 논의해봅시다

2024-09-27 07:21 UTC, Naknakk approved these changes
수고했어용
날짜 버튼 배경 슬라이드 되는 것 / 종료 날짜 로직 한번 이야기해봅시당~

2024-09-27 07:53 UTC, merged