Network/#248
Team-WSS/WSS-iOS pull request #295
Opened 2024-10-15 13:11 UTC by Guryss

### ⭐️Issue
close #
<br/>

### 🌟Motivation

<br/>

### 🌟Key Changes

<br/>

```swift
abc
```
<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-10-15 23:10 UTC, ena-isme approved these changes
공용컴포넌튼데 분기처리가 까다로웠다니, 디테일한 부분 말씀주시면 반영해볼게요~
수고하셨습니다.

2024-10-16 05:48 UTC, Guryss commented
> 공용컴포넌튼데 분기처리가 까다로웠다니, 디테일한 부분 말씀주시면 반영해볼게요~ 수고하셨습니다.

넹넹 노션에 적어놓을게염 !!!

2024-10-23 13:39 UTC, Naknakk requested changes
고생했습니당~!~! 짱구리스짱

2024-10-23 13:39 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
> +        let dropdownBottomButtonTapped: ControlEvent<Void>
W1
Input 네이밍이 DidTap 이렇게 가야할 것 같습니당!

2024-10-23 13:39 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
> +
W2
좀 더 깔끔하게 하려면 두 결과를 한 곳에서 모아서 다룰 수 있으면 좋을 것 같다는 생각이 들어요!


우선, 각 결과들을 모두 VM의 프로퍼티로 아래와 같이 빼고,
```swift
-- VM --
let showImproperAlertView = PublishRelay<Void>()
let showSpoilerAlertView = PublishRelay<Void>()
...
```

지금은 top, down버튼으로 나뉜 걸 enum을 만든 뒤,

```swift
enum DropdownButtonType {
    case top, bottom
}
```

 탭 이벤트에 mapping해서 하나의 tap input으로 바꾼 뒤에, 
 ```swift
 -- VM --
 Input {
    ...
     dropdownButtonDidTap: Observable<DropdownButtonType> 
 }
 
-- VC --
let dropdownButtonDidTap = Observable.merge(
     rootView.dropdownView.topDropdownButton.rx.tap.map { DropdownButtonType.top }
     rootView.dropdownView.bottomDropdownButton.rx.tap.map { DropdownButtonType.bottom }
)
이 이벤트를 VM의 dropdownButtonDidTap으로 넣어주고용
```
isMyFeed.value를 가져와서 4가지 분기 처리를 하면 좀 더 깔끔할 것 같기도 하네요!

```swift
-- VM --
input.dropdownButtonDidTap
    .map { ($0, isMyFeed.value) }
    .subscribe( ... , onNext: { owner, result in
        switch result {
        case (.bottom, false): owner.showImproperAlertView.accept(())
        case (.botton, true): owner.showSpoilerAlertView.accept(())
        ...
       }
    }
```

2024-10-24 12:52 UTC, hyowon612 approved these changes
LGTM !

2024-10-25 18:40 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailView.swift
>          profileView.snp.makeConstraints {
이 부분을 파악하고 있지 못했네요 고마워 낙낙!

`$0.top.equalTo(self.safeAreaLayoutGuide.snp.top)` 으로 수정해뒀습니당 👍

2024-10-25 18:40 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
> +        let dropdownBottomButtonTapped: ControlEvent<Void>
흐아아각

2024-10-25 19:01 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
> +
훨씬 깔끔하네요 대박쓰.. 전에 낙낙 코드 보면 Observable.merge를 엄청 잘 사용하시더라구요
확실히 rx를 하면 할수록 operator를 잘 활용해야겠다는 생각이 듭니다. 코드 개선 감사해용 >___<

2024-10-26 09:08 UTC, Naknakk approved these changes
고생했어요 짱짱~~~!~!~~ 엄청나다~~

2024-10-26 13:44 UTC, merged