Network/#252
Team-WSS/WSS-iOS pull request #296
Opened 2024-10-17 20:32 UTC by Guryss

### ⭐️Issue
close #
<br/>

### 🌟Motivation

<br/>

### 🌟Key Changes

<br/>

```swift
abc
```
<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-10-24 03:15 UTC, Naknakk requested changes
고생했습니당
텍스트 필드가 입력 후에 약간 밀리거나 , , , 하는 부분들이 있는데 디테일은 다음 PR을 기다릴게요!~!~

2024-10-24 13:13 UTC, hyowon612 reviewed
고생했습니다 !! 👍

2024-10-24 13:13 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailContentView.swift
> +                $0.height.equalTo(48)
W2
feedContent를 stackView로 감싸주면 레이아웃 업데이트 없이 
lineNovelView만 add, remove 해주는 방식으로도 구현할 수 있을 거 같아요!

2024-10-24 13:13 UTC, hyowon612 commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailReplyWritingView.swift
> +                    $0.leading.equalToSuperview().inset(6)
textView의 자체 인셋 때문에 textView내의 text가 밀려보여서 거기 맞춰준 거 같아용
textView에
```swift
$0.textContainer.lineFragmentPadding = 0
$0.textContainerInset = .zero
```
이거 적용해주면 해결됩니다!

2024-10-25 19:06 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailReplyWritingView.swift
> +                    $0.leading.equalToSuperview().inset(6)
이런 천재들ㄹㄹㄹㄹㄹㄹㄹㄹㄹ 고마워요

2024-10-25 19:06 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
> +            sendButtonTapped: rootView.replyWritingView.replyButton.rx.tap)
깔깔깔 고맙슴다

2024-10-25 19:11 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailContentView.swift
> +                $0.height.equalTo(48)
안그래두 지원언니꺼였나 하쿠꺼였나 stackView로 구현해둔 거 보긴 했는데
기존에 구현해둔 레이아웃 바꾸기 귀찮아서 `remakeConstraints` 를 사용했어여

2024-10-25 19:16 UTC, Guryss commented
> 고생했습니당 텍스트 필드가 입력 후에 약간 밀리거나 , , , 하는 부분들이 있는데 디테일은 다음 PR을 기다릴게요!~! 그리고 subscribe말고 do 쓰는 이유도 궁금해요!

음 일단 큰 이유에서는 subscribe는 좀 더 큰 단위의 이벤트(?)에서 사용하게 되는 것 같고, do는 이에 비교적 작은 단위의 이벤트 처리에 사용하는 것 같아요. 
더 깊이 들어가보면 저는 주로 `do`는 이벤트 흐름에 따른 데이터가 있으면 이를 가공하지 않을 때 주로 사용하는 것 같아요. 즉, 데이터가 아예 나오지 않는 `Observable<Void>`이거나 데이터가 나오지만 해당 데이터를 가공할 필요가 없는 상황일 때 ! 
그에 반대로 `subscribe` 는 이벤트 흐름에 따라 데이터를 가공해야 하는 상황에서 주로 사용하는 것 같습니다. 하하 근데 그게 코드에 잘 반영이 되었는진 잘 모르겠네영...

2024-10-26 09:10 UTC, Naknakk approved these changes
저도 do를 찾아봤는데 이벤트 흐름에 영향을 주지 않을 때 쓴다는데.. 정확히 subscribe랑 어떻게 다르게 쓰라는 건지 잘 모르겠더라구요 .. 자세한 설명 고마워요 !  좀 더 고민해보겠습니당 저두 . . . 고생했어요!

2024-10-28 12:14 UTC, hyowon612 approved these changes
쨩짱 🤩

2024-10-28 12:17 UTC, merged