[Fix] #297 - NormalSearch UI 수정 및 Cell 클릭 시 작품상세뷰로 이동
Team-WSS/WSS-iOS pull request #298
Opened 2024-10-20 10:24 UTC by Guryss

### ⭐️Issue
close #297 
<br/>

### 🌟Motivation
- NormalSearch 내 TextField UI 수정했습니다.
- Cell 클릭 시 해당 Cell에 대한 작품상세뷰로 이동하도록 반영했습니다. 
<br/>

### 🌟Key Changes
#### editing 여부에 따른 textField UI 변경
기존엔 editing 에 따른 UI 변화가 없었습니다. 
효원이가 구현해 둔 textField UI 및 update함수 반영했습니다 👍
<br/>

### 🌟Simulation

https://github.com/user-attachments/assets/8124eb3b-142b-40a2-9b91-0298724c0068

<br/>

### 🌟To Reviewer
- 없습니다
<br/>

### 🌟Reference
- 없습니다
<br/>

2024-10-24 03:32 UTC, Naknakk requested changes
고생해써요 레이아웃 하나만 봐주세용~

2024-10-24 03:32 UTC, Naknakk commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchView/NormalAssistantView/NormalSearchHeaderView.swift
> +            $0.bottom.equalToSuperview().inset(11)
W1
요거 12인 것 같아요 ! ? !

2024-10-24 14:01 UTC, hyowon612 approved these changes
굿굿굿👍👍👍

2024-10-25 19:23 UTC, Guryss commented on WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchView/NormalAssistantView/NormalSearchHeaderView.swift
> +            $0.bottom.equalToSuperview().inset(11)
흐이이이잇 이런 디테일쟁이!!!!!!!!!!! 고마어

2024-10-26 09:12 UTC, Naknakk approved these changes
짱짱!

2024-10-26 13:45 UTC, merged