[Fix] #395 - 마이페이지 네비게이션 수정 및 탭바 선택시 상단 스크롤 구현
Team-WSS/WSS-iOS pull request #396
Opened 2024-12-26 08:27 UTC by ena-isme

### ⭐️Issue
- close #395 
<br/>

### 🌟Motivation
마이페이지에서 스크롤 되었을 때 네비게이션 업데이트 UI 를 수정하였습니다.
추가로 탭바 선택시 상단으로 스크롤 되는 기능도 구현하였습니다 (피드, 마이페이지)

<br/>

### 🌟Key Changes

<br/>

기존에는  output.updateStickyHeader(
```swift
output.updateNavigationColor
            .asDriver()
            .drive(with: self, onNext: { owner, data in
                let (update, navigationTitle) = data
                owner.navigationController?.navigationBar.barTintColor = update ? .white : .clear
                owner.navigationController?.navigationBar.isTranslucent = !update
                owner.navigationItem.title = update ? navigationTitle : ""
            })
            .disposed(by: disposeBag)
        
        output.updateStickyHeader
            .asDriver()
            .drive(with: self, onNext: { owner, update in
                owner.rootView.scrolledStickyHeaderView.isHidden = !update
                owner.rootView.mainStickyHeaderView.isHidden = update
                owner.rootView.headerView.isHidden = update
            })
            .disposed(by: disposeBag)
```

<br/>

탭바 기능 구현 로직

WSSTabBarController 내부에서 구현되어 있으며
@Guryss 가 미리 해놓았던 scrollToTop 부분 참고하였습니다 😍

```swift
if let navigationController = viewController as? UINavigationController,
           let viewController = navigationController.viewControllers.first {
            
            switch viewController {
                
            case let homeViewController as HomeViewController:
                homeViewController.scrollToTop()
                
            case let feedViewController as FeedViewController:
                if tabBarController.selectedViewController == navigationController {
                    feedViewController.scrollToTop()
                }
                
            case let myPageViewController as MyPageViewController:
                myPageViewController.scrollToTop()
                
            default:
                break
            }
        }
```
<br/>

### 🌟Simulation

<br/>

### 🌟To Reviewer

<br/>

### 🌟Reference

<br/>

2024-12-26 17:07 UTC, Naknakk requested changes
고생했습니다! 너무 좋네요!!
네비게이션 바 하단의 구분선이 없으면 좋겠다고 전에 디자인 측에서 이야기했던게 생각나서, 
NovelDetailViewContoller의 updateNavigationBarStyle(offset:) 메서드에 있는 UI 적용 방식으로 네비게이션 바를 설정해주면 더 좋을 것 같아요!
다른 뷰는 다 네비게이션 바 하단 구분선이 없어서용!

2024-12-27 10:01 UTC, Guryss reviewed
수고하셨어요!!! 

근데 마이페이지 드롭다운을 클릭하면 차단하기 버튼이 바로 아래에 안생기고 ... 다른 곳에 생겨요 🥲
스크롤하면 저렇게 위치가 변하네요 !!

<img src="https://github.com/user-attachments/assets/4b1acc1e-3f95-4b72-9a12-46d6cbbf41e0" width=300>

2025-01-01 08:32 UTC, ena-isme commented
@guryss 
저번에 실기기 에러 재연에 실패하여 이번 PR 에서는 수정안하였습니당
호옥시 다시 이슈 발생하면 바로 말씀주세요!

2025-01-02 08:19 UTC, Guryss reviewed
수고하셨습니당! 
리뷰 하나만 확인 해주세요 >.<

2025-01-02 08:19 UTC, Guryss commented on WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
> +        self.navigationController?.navigationBar.shadowImage = UIImage()
`setNavigationBar` 함수에서 이 두 코드만 추가된거라면 매개변수 하나를 추가해서 **하나의 함수**로만 가져가는 게 어떨까요?

```
func setNavigationBar(title: String, left: UIButton?, right: UIButton?, hasUnderline: Bool = false) {
    ....
    if hasUnderline {
        self.navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)
        self.navigationController?.navigationBar.shadowImage = UIImage()
    }
}
```

2025-01-02 08:36 UTC, ena-isme commented on WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
> +        self.navigationController?.navigationBar.shadowImage = UIImage()
좋은 것 같아요! 몇가지 생각해본 게 있는데

상황) 현재 NovelDetail, MyPage 에서만 저 메서드를 쓰고 있음
1. 모든 곳에서 네비게이션바에 언더바가 필요없다면, 분기처리 없이 그냥 기존 함수에 저 코드를 추가해도 되지 않나?
2. 기존 잘돌아가고 있는 코드를 굳이 건들지 않는게 낫다면, StickyHeader 를 사용하는NovelDetail, MyPage 에서만 setNavigationBarWithoutUnderline 함수를 쓰는 건 어떨까?

하는 생각에 함수를 둘로 뺐던 거 였어요! 어떤 게 나을까요?
우선 NovelDetail 부분이 윤학오빠라 윤학오빠랑 코드 통일은 해야 할 것 같아요~!

2025-01-02 08:41 UTC, Guryss commented on WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
> +        self.navigationController?.navigationBar.shadowImage = UIImage()
음 약간 개인 취향의 영역 같아보이긴 해요! 
근데 매개변수에 기본값을 이미 false로 해두어서 기존 다른 코드들은 건들일 필요는 없을 것 같구 현재 추가해야하는 부분에만 hasUnderline = true로 해두면 될 것 같긴 합니동

2025-01-02 08:43 UTC, ena-isme commented on WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
> +        self.navigationController?.navigationBar.shadowImage = UIImage()
오케잉 그럼 구리스 추천대로 해보께융

2025-01-02 09:02 UTC, ena-isme commented
@Naknakk  NovelDetail 도 가능하다면 저 함수로 통일 부탁해용!

2025-01-02 09:06 UTC, Guryss approved these changes
굿!!!!! 나중에 윤학오빠도 이 함수로 넣어서 코드 수정하면 좋겠네요!

2025-01-03 03:13 UTC, hyowon612 approved these changes
LGTM!!

2025-01-03 03:15 UTC, merged